fix: Add missing include statement
Threw a weird error:
BamBlockReader.hpp:71:34: error: ‘gzip_error’ in namespace ‘boost::iostreams’ does not name a type